swagger: '2.0'
info:
  title: Mineplex
  description: Public API for Mineplex PC
  version: "1.0.0"
host: api.mineplex.com
basePath: /pc
schemes:
  - https
produces:
  - application/json
securityDefinitions:
  apiKey:
    type: apiKey
    name: apiKey
    in: query
paths:
  /player/{player}:
    get:
      summary: Get basic info about a player
      parameters:
        - name: player
          in: path
          description: Name or UUID of the player
          required: true
          type: string
          format: uuid or player name
      tags:
        - Player
      security:
      - apiKey: []
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/Player'
        404:
          description: Player not found
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /player/{player}/status:
    get:
      summary: Get a player's online status
      parameters:
        - name: player
          in: path
          description: Name or UUID of the player
          required: true
          type: string
          format: uuid or player name
      tags:
        - Player
      security:
      - apiKey: []
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/PlayerStatus'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /player/{player}/friends:
    get:
      summary: Get a player's friend list
      parameters:
        - name: player
          in: path
          description: Name or UUID of the player
          required: true
          type: string
          format: uuid or player name
      tags:
        - Player
      security:
      - apiKey: []
      responses:
        200:
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/PlayerBase'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /network:
    get:
      summary: Get basic network status
      description: |
        Returns the current player count for EU and US networks, along with their MOTD
      tags:
        - Network
      security:
      - apiKey: []
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/Network'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /network/{region}:
    get:
      summary: Get status of network region
      parameters:
        - name: region
          in: path
          description: Network Region
          required: true
          type: string
          format: US|EU
      tags:
        - Network
      security:
      - apiKey: []
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/Region'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /network/{region}/{server}:
    get:
      summary: Get status of specific server
      parameters:
        - name: region
          in: path
          description: Network Region
          required: true
          type: string
          format: US|EU
        - name: server
          in: path
          description: Server
          required: true
          type: string
      tags:
        - Network
      security:
      - apiKey: []
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/MinecraftServer'
        404:
          description: Minecraft server not found
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /amplifier:
    get:
      summary: Get Amplifiers
      description: |
        Returns a dictionary mapping amplifier groups to an array of Amplifiers.
      tags:
        - Amplifier
      security:
      - apiKey: []
      responses:
        200:
          description: Success
          schema:
            type: object
            additionalProperties:
              type: array
              items:
                $ref: '#/definitions/Amplifier'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /amplifierGroup:
    get:
      summary: Get Amplifier Groups
      description: |
        Returns an array of strings representing all available amplifier groups
      tags:
        - Amplifier
      security:
      - apiKey: []
      responses:
        200:
          description: Success
          schema:
              type: array
              items:
                type: string
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /amplifier/{amplifiergroup}:
    get:
      summary: Get Amplifiers from Amplifier Group
      description: |
        Returns an array of amplifiers for that group
      parameters:
        - name: amplifiergroup
          in: path
          description: Amplifier Group
          required: true
          type: string
      tags:
        - Amplifier
      security:
      - apiKey: []
      responses:
        200:
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/Amplifier'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /fountain:
    get:
      summary: Get current Gem Fountain status
      description: |
        Returns the current status of the Gem Fountain for Weekend Brawl
      tags:
        - Fountain
      security:
      - apiKey: []
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/Fountain'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  PlayerBase:
    type: object
    required:
    - name
    - uuid
    properties:
      name:
        type: string
        description: The player's name
      uuid:
        type: string
        description: The player's UUID, including dashes
  Player:
    type: object
    required:
    - name
    - uuid
    - rank
    - lastLogin
    - status
    - friends
    properties:
      name:
        type: string
        description: The player's name
      uuid:
        type: string
        description: The player's UUID, including dashes
      rank:
        type: string
      lastLogin:
          type: string
          format: date-time
      level:
        $ref: '#/definitions/PlayerLevel'
      status:
        $ref: '#/definitions/PlayerStatus'
      friends:
          type: array
          items:
            $ref: '#/definitions/PlayerBase'
  PlayerLevel:
    type: object
    required:
    - value
    - color
    properties:
      value:
        type: integer
        description: The player's Mineplex level
      color:
        type: string
        description: The color coresponding to the level value
  PlayerStatus:
    type: object
    required:
    - online
    properties:
      online:
        type: boolean
        description: Is the player online right now?
      server:
        type: string
        description: The server the player is connected to. Only present if online is true.
  Fountain:
    type: object
    required:
    - brawlActive
    - percent
    properties:
      brawlActive:
        type: boolean
        description: Is the Weekend Brawl currently active?
      percent:
        type: integer
        description: The percent filled the Fountain currently is, represented as an interger from 0-300
  Amplifier:
    type: object
    required:
      - playerName
      - uuid
      - duration
      - activationTime
      - multiplier
      - startTime
      - endTime
    properties:
      playerName:
        type: string
        description: The player that activated this Amplifier
      uuid:
        type: string
        description: The UUID of the player that activated this Amplifier
      duration:
        type: integer
      activationTime:
        type: string
        format: date-time
      multiplier:
        type: number
      startTime:
        type: string
        format: date-time
      endTime:
        type: string
        format: date-time
  MinecraftServer:
    type: object
    required:
      - name
      - group
      - motd
      - playerCount
      - maxPlayerCount
    properties:
      name:
        type: string
        description: The name of the Minecraft server (unique identifier)
      group:
        type: string
        description: The server group this server belongs to
      motd:
        type: string
        description: Current MOTD of the server
      playerCount:
        type: integer
        description: The number of players currently logged into this server
      maxPlayerCount:
        type: integer
        description: The max players this server can hold
  Network:
    type: object
    required:
      - US
      - EU
      - playerCount
    properties:
      US:
        $ref: '#/definitions/Region'
      EU:
        $ref: '#/definitions/Region'
      playerCount:
        type: integer
        description: The total number of players logged into Mineplex
  Region:
    type: object
    required:
      - status
      - playerCount
      - motd
    properties:
      status:
        type: string
        description: The current status of this network region
      playerCount:
        type: integer
        description: The number of players logged into this network region
      motd:
        $ref: '#/definitions/Motd'
  Motd:
    type: object
    required:
      - mainLine
      - otherLines
    properties:
      mainLine:
        type: string
        description: The main line of the motd message
      otherLines:
        type: array
        items:
          type: string
        description: The number of players logged into this network region
      motd:
        $ref: '#/definitions/PlayerStatus'
  Error:
    type: object
    required:
    - statusCode
    properties:
      statusCode:
        type: integer
        description: HTTP status code sent with this error
      error:
        type: string
        description: Description of the error
